import type { Metadata } from "next";
import { Special_Elite } from "next/font/google";
import Header from "./components/header";
import Footer from "./components/footer";

import "./globals.css";

const inter = Special_Elite({ weight: ["400"], preload: false });

export const metadata: Metadata = {
  title: "Criminal Databases",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );

}
